font_family      Maple Mono Bold

shell zsh

font_size 14.0

shell_integration no-cursor
cursor_shape beam

confirm_os_window_close 0

# Colors
cursor               #cc9966

selection_background #cccccc
selection_foreground #333333

background           #333333
foreground           #cccccc

color0               #666666
color1               #cc6699
color2               #99cc66
color3               #cc9966
color4               #6699cc
color5               #9966cc
color6               #66cc99
color7               #cccccc
color8               #999999
color9               #ff99cc
color10              #ccff99
color11              #ffcc99
color12              #99ccff
color13              #cc99ff
color14              #99ffcc
color15              #ffffff